### ISSUE TITLE
Getting error Cannot read property 'getBytes' of null

### ISSUE THREAD

**Issue by Harrrrry** [ravshansbox/browser-crypto#5]
Hello,

(node:14792) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getBytes' of null
    at Rand._rand (D:\node project\MiaWallet\node_modules\@ravshansbox\browser-crypto\dist\browser-crypto.js:6155:17)

Any help?

**Comment by ravshansbox** [comment]
@Harrrrry thank you for reaching out, can you share a smallest possible code where we can reproduce the issue?

**Comment by Harrrrry** [comment]
Hello @ravshansbox 

`const {
  Buffer,
  createECDH,
  createCipheriv,
  createDecipheriv,
} = require("@ravshansbox/browser-crypto");`

` const ecdh1 = createECDH("secp256k1");

    const publicKey1 = ecdh1.generateKeys();

    const secret1 = ecdh1.computeSecret(publicKey2);

    const iv = Buffer.alloc(16);
    const data = Buffer.from("abcdef");

    const cipher = createCipheriv("aes256", secret1, iv);
    const encrypted = Buffer.concat([cipher.update(data), cipher.final()]);`

**Comment by ravshansbox** [comment]
@Harrrrry, I've published a new version, can you give a try?

**Comment by ravshansbox** [comment]
BTW, you can use `browser-crypto` package as well if your prefer shorter name, they are both the same.

**Comment by ravshansbox** [comment]
I hope issue is fixed. Closing.
